# Generated by Django 5.2.8 on 2025-11-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Markdown content is supported. Use ```language for code blocks.'),
        ),
    ]
